# Setup
title:               Arkadiusz Nitschke
tagline:             'Komornik sądowy'
description:         'Komornik Sądowy przy Sądzie Rejonowym w Oleśnicy'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
# plugins:
  

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

include: 
  - _pages
